name: tugasbesar
description: A comprehensive news application with real-time features

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.2.1
  share_plus: ^11.0.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/CobraNews.jpeg"


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
